### ISSUE TITLE
Unable to open MDB files -> RangeError: offset is not uint

### ISSUE THREAD

**Issue by ahaganDEV** [andipaetzold/mdb-reader#213] opened 2022-05-10 12:18 UTC
Mode: Browser (Chrome)
mdb-reader version: 2.2.2
Node version: 14.19.1
Buffer: 6.0.3

When using this library, and passing in an MDB file from the test examples, e.g. test.mdb (test/data/v2000) when constructing a reader, I receive the error: `Range Error: offset is not uint`.

After debugging in Chrome, this is caused by: complexOrLong.js.readComplexOrLong(). This is calling  buffer.readInt32LE() without passing an offset in. Other articles suggests that offset has a default version of 0 https://www.geeksforgeeks.org/node-js-buffer-readint32le-method/.

The buffer package however requires a value to be passed in https://github.com/feross/buffer/blob/795bbb5bda1b39f1370ebd784bea6107b087e3a7/index.js#L1127. 

In this case should this package's code just be passing 0 in as the parameter value for offset? 

If I manually edit those functions (integer.js, complexOrLong.js, float.js) in the node_modules folder for this package to pass 0 in as the index, the MDBReader is constructed and I can then query the data within it. Is there a mismatch between node versions?

**Comment by andipaetzold** [comment] 2022-05-10 21:49
:wave: 

Unfortunately, I am unable to reproduce your issue. When running the browser example locally and reading all data from a database with complex/long columns, everything works fine.

Looking at the code of `readInt32LE`, I am not sure why it would fail for `offset` being undefined as [the first line](https://github.com/feross/buffer/blob/795bbb5bda1b39f1370ebd784bea6107b087e3a7/index.js#L1310) (`offset = offset >>> 0`) turns the `undefined` to `0` which passes the offset check.

I have in mind though that I ran into some issues like this before. But I'd like to be able to reproduce the issue myself before updating the code.

**Comment by sspa-dhayes** [comment] 2022-05-13 12:49
this is the same thing I was seeing in: https://github.com/andipaetzold/mdb-reader/issues/207#issue-1226890961

...i thought it was a webpack issue, but tried with a setup similar to ahaganDEV

my workaround was to add the zero index when reading from the buffers in:
\src\data\bigint.ts
<img width="439" alt="image" src="https://user-images.githubusercontent.com/8457488/168285872-8e62b00c-6b37-47da-ac2d-e1949cbbe59e.png">

\src\data\byte.ts
<img width="393" alt="image" src="https://user-images.githubusercontent.com/8457488/168285935-bb4bf462-707b-43fd-a9b5-1a338d216870.png">

\src\data\complexOrLong.ts
<img width="458" alt="image" src="https://user-images.githubusercontent.com/8457488/168286328-b7750a6e-5201-4630-a371-a2e3cbdee9b6.png">


\src\data\datetime.ts
<img width="464" alt="image" src="https://user-images.githubusercontent.com/8457488/168286078-2f5d689e-79de-4851-9aa7-5b47d1999b0e.png">

\src\data\double.ts
<img width="451" alt="image" src="https://user-images.githubusercontent.com/8457488/168286143-d639189d-c0f8-4662-b058-1e685e90cc7b.png">

\src\data\float.ts
<img width="409" alt="image" src="https://user-images.githubusercontent.com/8457488/168286423-40eba9f9-76c1-4a2d-9811-180a0f6b1c74.png">

\src\data\integer.ts
<img width="468" alt="image" src="https://user-images.githubusercontent.com/8457488/168286506-1637140f-835c-4e1f-bb39-b0af5a96aa68.png">

**Comment by andipaetzold** [comment] 2022-05-13 12:54
@sspa-dhayes Could you provide a sample repo or code sandbox so I can reproduce the issue? For me things worked in the browser :( 

That way I can also add tests to avoid this from happening in the future (by adding tests/linting).

I am happy to release a new version once I was able to reproduce. The required changes seem to be quite minimal.

**Comment by andipaetzold** [comment] 2022-05-19 15:17
@ahaganDEV @sspa-dhayes I am very happy to update this package to fix your issue. But first, I'd like to be able to reproduce it. I tried to use the package within the browser and everything worked for me. 

I only want to prevent releasing a "fix" to an error that is actually caused by webpack (config) and not of this package.

**Comment by ahaganDEV** [comment] 2022-05-23 07:51
I don't believe the issue is webpack? When debugging within the browser, I can confirm that it is using the Buffer package. I forked the mdb-library library and amended some of the functions that interact with Buffer and worked perfectly fine.   Chaging:

export function readComplexOrLong(buffer: Buffer): number {
    return buffer.readInt32LE();
}

to:

export function readComplexOrLong(buffer: Buffer): number {
    return buffer.readInt32LE(0);
}

**Comment by andipaetzold** [comment] 2022-05-24 22:18
I tried to reproduce the issue by moving the browser example to webpack: https://github.com/andipaetzold/mdb-reader-issue-218.I don' receive any errors when loading a database.

Can you please check what code is executed when calling `readInt32LE`. Is it really this: https://github.com/feross/buffer/blob/795bbb5bda1b39f1370ebd784bea6107b087e3a7/index.js#L1309-L1317 ? Or are you maybe using an older version of the package where the offset doesn't default to 0.

**Comment by andipaetzold** [comment] 2022-06-17 15:40
Closing because I cannot reproduce the issue.

Feel free to reopen if you can provide a repo or similar that shows the issue.

**Closed by andipaetzold** 2022-06-17 15:40 UTC
Labels: bug

**Comment by mnappo** [comment] 2022-10-08 00:14
@ahaganDEV If you are still having this issue - my post to #207 worked for me. Webpack/CRA was not using the buffer package. Apparently Webpack 4 shims some nodejs functions on its own...
